"""
Report Agent
────────────
Compiles all agent outputs into a structured Markdown report containing:
  - Executive summary
  - Methodology
  - Findings & insights (from execution stdout)
  - Visualisation links (from execution artifacts)
  - Appendix: generated code
  - Metadata (token usage, timings)
"""

from __future__ import annotations

import json
import logging
import os
import time
from pathlib import Path
from typing import Any

from agents.base import BaseAgent
from agents.state import AgentState
from config.settings import settings

logger = logging.getLogger(__name__)

_SYSTEM_PROMPT = """\
You are a technical report writer. Given structured information about a completed
AI analysis workflow, produce a professional Markdown report.

The report must include these sections (use ## headings):
1. Executive Summary
2. Methodology
3. Key Findings & Insights
4. Visualisations (list image paths)
5. Conclusions & Recommendations
6. Appendix A – Generated Code

Write in clear, professional language. Use bullet points for lists of findings.
Be factual — only state what the data/outputs actually show.
"""


class ReporterAgent(BaseAgent):
    """Compiles execution results into a structured final report."""

    LLM_ROLE = "primary"

    def __init__(self) -> None:
        super().__init__("ReporterAgent")

    def run(self, state: AgentState) -> dict[str, Any]:
        task = state.get("original_task", "")
        subtasks = state.get("subtasks", [])
        research = state.get("research_summary", "")
        stdout = state.get("execution_stdout", "")
        artifacts = state.get("execution_artifacts", [])
        code = state.get("generated_code", "")
        token_usage = state.get("token_usage", {})
        timings = state.get("step_timings", {})
        sources = state.get("research_sources", [])

        # ── Extract insights from stdout ──────────────────────────────────────
        insights_json = _extract_json_summary(stdout)
        insights_text = json.dumps(insights_json, indent=2) if insights_json else stdout[:2000]

        # ── Build visualisation section ───────────────────────────────────────
        viz_section = ""
        png_artifacts = [a for a in artifacts if a.endswith(".png")]
        if png_artifacts:
            viz_section = "\n".join(f"- `{a}`" for a in png_artifacts)
        else:
            viz_section = "_No visualisations generated._"

        prompt = f"""
Task: {task}

Subtasks completed:
{chr(10).join(f"{i+1}. {t}" for i, t in enumerate(subtasks))}

Research summary:
{research[:1500] or '(none)'}

Execution output / insights:
{insights_text}

Artifacts produced:
{chr(10).join(f"- {a}" for a in artifacts) or '(none)'}

Sources consulted:
{chr(10).join(f"- {s}" for s in sources[:5]) or '(none)'}

Code used (first 1200 chars):
```python
{code[:1200]}
```

Write a professional Markdown report.
"""
        response = self.llm.complete(prompt, system_prompt=_SYSTEM_PROMPT)
        report_md = response["content"]

        # ── Append metadata footer ────────────────────────────────────────────
        total_tokens = sum(token_usage.values())
        total_time = sum(timings.values())
        report_md += f"""

---
## Workflow Metadata

| Metric | Value |
|--------|-------|
| Total tokens used | {total_tokens:,} |
| Total wall time | {total_time:.2f}s |
| Artifacts | {len(artifacts)} |
| Subtasks | {len(subtasks)} |

*Report generated by Autonomous Multi-Agent AI System*
"""

        # ── Save report to disk ───────────────────────────────────────────────
        task_id = state.get("task_id", "unknown")
        report_path = settings.ARTIFACTS_DIR / f"{task_id}_report.md"
        report_path.write_text(report_md, encoding="utf-8")
        self.logger.info("Report saved to %s", report_path)

        return {
            "final_report": report_md,
            "report_path": str(report_path),
            "workflow_status": "complete",
        }


def _extract_json_summary(stdout: str) -> dict | None:
    """Try to parse the last JSON object printed by generated code."""
    import re

    matches = re.findall(r"\{[^{}]*\}", stdout, re.DOTALL)
    for m in reversed(matches):
        try:
            return json.loads(m)
        except json.JSONDecodeError:
            continue
    return None
